name: User Acceptance Tests

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '!gh-pages'

jobs:

  installDependencies:

    name: User Acceptance Tests

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        uses: actions/setup-node@v1
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
        with:
          node-version: ${{ matrix.node-version }}
          args: install
      - run: ls -laGF
      - run: npm --version
      - run: node --version
      - run: npm run build
      - run: ls -laGF dist
      - name: npm run test:uat
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
        with:
          args: npm run test:uat

#  build:
#
#    runs-on: ubuntu-latest
#
#    strategy:
#      matrix:
#        node-version: [14.x]
#
#    steps:
#    - uses: actions/checkout@v1
#    - name: Use Node.js ${{ matrix.node-version }}
#      uses: actions/setup-node@v1
#      with:
#        node-version: ${{ matrix.node-version }}
#    - name: npm run test:uat
#      run: |
#        npm ci
#        npm run test:uat
#      env:
#        CI: true
