name: User Acceptance Tests

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '!gh-pages'

#jobs:
#  user-acceptance-tests:
#    runs-on: ubuntu-latest
#
#    strategy:
#      matrix:
#        node-version: [ 14.x ]
#
#    steps:
#      - uses: actions/checkout@v2
#      - name: Use Node.js ${{ matrix.node-version }}
#        uses: actions/setup-node@v1
#        with:
#          node-version: ${{ matrix.node-version }}
#      - uses: microsoft/playwright-github-action@v1
#      - name: npm install, build, and test
#        run: |
#          npm ci
#          npm run build
#          npx playwright install-deps
#          npm run test:uat
#        env:
#          CI: true
#      - name: 'Upload Artifact'
#        uses: actions/upload-artifact@v2
#        with:
#          name: screenshot
#          path: screenshot.png
#          retention-days: 5


jobs:
  user-acceptance-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: microsoft/playwright-github-action@v1
      - name: Install dependencies and run tests
        run: npm install && npm run test:uat
